"""add lat/lng em mercados e preferencias de localizacao em usuarios

Revision ID: 2d8dadefa653
Revises: 
Create Date: 2025-08-27 18:14:14.827639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8dadefa653'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mercados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raio_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('modo_localizacao', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cidade_manual', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('uf_manual', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('criado_em')
        batch_op.drop_column('uf_manual')
        batch_op.drop_column('cidade_manual')
        batch_op.drop_column('modo_localizacao')
        batch_op.drop_column('raio_km')

    with op.batch_alter_table('mercados', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
